### ISSUE TITLE
need to fix scroll

### ISSUE THREAD

**Issue by prashantpandey9** [Kabi4/Google-Engine-Copied#1]
Hey I just went through your website and it seems there is a horizontal scrolling in it

**Comment by Kabi4** [comment]
Ya i have seen it but i tried as hell to fix it everywhere i hvve put overflowX hidden but seems its not working

**Comment by prashantpandey9** [comment]
try to add and remove component in your result page. It will give you which component is going outside the container/

**Comment by Kabi4** [comment]
Yep no components is going outside the container as we are going in vertiacaldirection the scroll bar is shown due to which as we have 100vw we facing an issue of having horizontal scroll too if we use Element:webkit-scrollbar{display: hidden;} it will be gone for sure :)

**Comment by prashantpandey9** [comment]
Also try using max-width 100%

**Comment by prashantpandey9** [comment]
may be the max-width in body could solve your issue

**Comment by Kabi4** [comment]
:) i have mentoined why the horizaontal scroll is visible
